# These are supported funding model platforms

# github: [YOUR_GITHUB_USERNAME]
# patreon: YOUR_PATREON_USERNAME
# open_collective: YOUR_OPEN_COLLECTIVE
# ko_fi: YOUR_KO_FI_USERNAME
# custom: ["https://your-website.com/donate"]
