# Pre-commit hooks for security checks
# Install: pip install pre-commit
# Setup: pre-commit install

repos:
  # Security checks
  - repo: local
    hooks:
      # Check for secrets
      - id: no-secrets
        name: Check for hardcoded secrets
        entry: bash -c 'if grep -r -E "(password|secret|api_key|token)\s*=\s*['\''\"'\''][^'\''\"'\'']{20,}['\''\"'\'']" backend/src --include="*.ts" --include="*.js" | grep -v "process.env"; then echo "❌ Hardcoded secrets found"; exit 1; fi'
        language: system
        pass_filenames: false

      # Check for eval()
      - id: no-eval
        name: Check for eval() usage
        entry: bash -c 'if grep -r "eval(" backend/src --include="*.ts" --include="*.js"; then echo "❌ eval() found"; exit 1; fi'
        language: system
        pass_filenames: false

      # Run security audit (backend)
      - id: security-audit-backend
        name: Security audit (backend)
        entry: bash -c 'cd backend && npm audit --audit-level=high'
        language: system
        pass_filenames: false
        always_run: true

      # Run security tests
      - id: security-tests
        name: Run security tests
        entry: bash -c 'cd backend && npm test -- security.test.ts --silent'
        language: system
        pass_filenames: false
        always_run: true

      # Custom security audit
      - id: custom-security-audit
        name: Custom security audit
        entry: bash -c 'cd backend && node scripts/security-audit.js'
        language: system
        pass_filenames: false
        always_run: true

  # Check for .env files
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-added-large-files
        args: ['--maxkb=500']
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: detect-private-key

  # TypeScript/JavaScript linting
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.56.0
    hooks:
      - id: eslint
        files: \.[jt]sx?$
        types: [file]
        additional_dependencies:
          - eslint@8.56.0
          - '@typescript-eslint/eslint-plugin@6.21.0'
          - '@typescript-eslint/parser@6.21.0'

