# pnpm workspace configuration
# Определяет структуру монорепозитория

packages:
  # Основные приложения
  - 'apps/*'
  # Переиспользуемые пакеты
  - 'packages/*'
  
# Исключения (опционально)
# exclude:
#   - '**/test/**'
#   - '**/dist/**'

