# pnpm workspace configuration
# Определяет структуру монорепозитория

packages:
  # Основные приложения
  - 'backend'
  - 'frontend'
  - 'bot'

# Исключения (опционально)
# exclude:
#   - '**/test/**'
#   - '**/dist/**'

